parserOptions:
  ecmaVersion: latest
  sourceType: 'module'

env:
  es2022: true
  browser: true

extends:
  - 'htmlacademy/vanilla'

rules:
  sort-imports:
    - error
    - ignoreCase: true
      ignoreDeclarationSort: true

  import/order:
    - error
    - groups:
        - index
        - sibling
        - parent
        - internal
        - external
        - builtin
        - object
        - type
